#!/usr/bin/env python
"""
Create a static transform between the Franka Emika (Panda) apriltag and the world frame
"""
import rospy
import tf2_ros
from geometry_msgs.msg import TransformStamped
import math

if __name__ == "__main__":
    rospy.init_node("fixed_tag")

    # Set up static broadcaster
    static_broadcaster = tf2_ros.StaticTransformBroadcaster()

    # Create the transform between the robot tag and the world
    world_tag_tf = TransformStamped()
    world_tag_tf.header.stamp = rospy.Time.now()
    world_tag_tf.header.frame_id = "world"
    world_tag_tf.child_frame_id = "panda_tag_static"

    # Place robot apriltag centered and in front of base
    world_tag_tf.transform.translation.x = 0.120 # 120 mm (center of 60 mm apriltag will be +(83 + 30 + length of whitespace mm) in +x direction )
    world_tag_tf.transform.translation.y = 0
    world_tag_tf.transform.translation.z = 0
    world_tag_tf.transform.rotation.x = 0
    world_tag_tf.transform.rotation.y = 0
    world_tag_tf.transform.rotation.z = 0
    world_tag_tf.transform.rotation.w = 1

    static_broadcaster.sendTransform(world_tag_tf)

    rospy.spin()