#!/usr/bin/env python3

import rospy
import actionlib
from franka_gripper.msg import MoveGoal, MoveAction, GraspGoal, GraspAction, GraspEpsilon

'''This is a testing node to test the grasp action of the gripper. This node uses the GraspAction action.
'''

if __name__ == '__main__':
    rospy.init_node('grasp')
    client = actionlib.SimpleActionClient('/franka_gripper/grasp', GraspAction)
    client.wait_for_server()
    goal = GraspGoal(width = 0.065, epsilon = GraspEpsilon(0.035, 0.035), speed = 0.005, force = 4)
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(5.0))
