#!/usr/bin/env python3
import rospy
import actionlib
from franka_gripper.msg import MoveGoal, MoveAction

'''This is a testing node to test the opening action of the gripper. This node uses the MoveAction action.
'''

if __name__ == '__main__':
    rospy.init_node('grippergoal')
    client = actionlib.SimpleActionClient('/franka_gripper/move', MoveAction)
    client.wait_for_server()
    goal = MoveGoal(width = 0.07, speed = 0.08)
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(5.0))
