#! /usr/bin/env python

import rospy
import actionlib
import actionlib_msgs
import sys
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from moveit_msgs.msg import MoveItErrorCodes
from moveit_commander.conversions import pose_to_list
from math import pi
from std_srvs.srv import Empty, EmptyResponse, SetBool, SetBoolResponse


if __name__ == "__main__":

        scene = moveit_commander.PlanningSceneInterface()
        robot = moveit_commander.RobotCommander()

        group_name = "panda_arm"

        move_group = moveit_commander.MoveGroupCommander(group_name)
        display_trajectory_publisher = rospy.Publisher('/move_group/display_planned_path',movei


        joint_goal = move_group.get_current_joint_values()
        joint_goal[5] = joint_goal[5]+pi/8

        move_group.go(joint_goal, wait=True)
        move_group.stop()
