#!/usr/bin/env python3
# MixGui node
# RKS

# Project imports
from final_project_mixotics.srv import ConfirmOrder, ConfirmOrderResponse
from final_porject_mixotics.srv import Order, OrderRequest

# Python imports

# 3rd-party imports
import rospy
import pygame


class MixGui:
    """
    ROS Node managing human-interface with the robot. This node records and
    sends orders from clients and displays when the order is complete

    SERVICES:
        confirm_order ConfirmOrder
    
    CLIENTS:
        process_order Order
    """
    def __init__(self):
        """
        Constructor of ROS Node MixGui class. Creates the service, client and
        gui
        """
        # init node and pygame
        rospy.init_node("mix_gui")
        pygame.init()
        # Constants
        self._SCREEN_WIDTH = 1500
        self._SCREEN_HEIGHT = 1000
        self._BACKGROUND_RGB = [255, 255, 255]
        # Set up service
        self._confirm_service = rospy.Service('confirm_order', ConfirmOrder, self._handle_confirm_service)
        # Set up clients
        self._process_client = rospy.ServiceProxy('process_order', Order)

    def _handle_confirm_service(self, req):
        """
        Display to client when order is complete
        """
        pass


# Activate 'mix_gui' node
def main():
    """
    Activation function for order handler
    """
    mix_gui = MixGui()

# Main Exceution loop
if __name__ == "__main__":
    try:
        main()
    # If something kills this node, have it die
    except rospy.ROSInterruptException:
        pass
