#!/usr/bin/env python3
import rospy
import actionlib
from franka_gripper.msg import MoveGoal, MoveAction, GraspGoal, GraspAction, GraspEpsilon

'''This is a testing node to test the squeeze action of the gripper. This node uses the GraspAction action.
'''

if __name__ == '__main__':
    rospy.init_node('grasp')
    client = actionlib.SimpleActionClient('/franka_gripper/grasp', GraspAction)
    client.wait_for_server()
    goal = GraspGoal(width = 0.002, epsilon = GraspEpsilon(0.1, 0.1), speed = 3, force = 20)
    client.send_goal(goal)
    client.wait_for_result(rospy.Duration.from_sec(5.0))
