#!/usr/bin/env python

import rospy
import cv2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

class Vision:
    
    def __init__(self):
        self.sub_img = rospy.Subscriber('/camera/color/image_raw', Image, self.img_callback)
        self.bridge = CvBridge()

    def img_callback(self, img):
        try:
            image = self.bridge.imgmsg_to_cv2(img, 'passthrough')
        except CvBridgeError as e:
            rospy.logerr('CvBridge Error: {0}'.format(e))
        self.show_image(image)
        
    def show_image(self, img):
        cv2.namedWindow('Image Window', 1)
        cv2.imshow('Image Window', img)
        cv2.waitKey(3)

def main():
    """ The main() function. """
    rospy.init_node('vision')
    v = Vision()
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass