# Request for order_handler/update_inventory service
# Given an ingredient name and whether the ingredient is available
string ingredient
bool available # True if inventory has ingredient
---
# Empty Response