# Request for order_handler/order service
# Given an list of orders, return order_number mapping to orders
string[] orders
---
# Positive number if order was valid, 0 if order was not
uint8 order_num 
string msg