# Request/Response for pour service
# Tells the robot where to pour ingredient and how much to pour

uint16 instr_id  # Id of the instruction
uint8  cup_id    # Cup to pour amount into
uint8  amount_ml # amount to pour
---
# Empty Response